/*!
Copyright (c) 2013, Groupon, Inc.
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:

Redistributions of source code must retain the above copyright notice,
this list of conditions and the following disclaimer.

Redistributions in binary form must reproduce the above copyright
notice, this list of conditions and the following disclaimer in the
documentation and/or other materials provided with the distribution.

Neither the name of GROUPON nor the names of its contributors may be
used to endorse or promote products derived from this software without
specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var abbreviate, asRegExp, assert, cache$, contains, error, global, green, handleArgs, implodeNicely, isArray, isEqual, isFunction, isNumber, isRegExp, isString, name, nameNegative, pluck, red, stringify, toString, type;
  global = Function('return this')();
  cache$ = null != global._ ? global._ : require('underscore');
  contains = cache$.contains;
  isEqual = cache$.isEqual;
  isString = cache$.isString;
  isNumber = cache$.isNumber;
  isRegExp = cache$.isRegExp;
  isArray = cache$.isArray;
  isFunction = cache$.isFunction;
  pluck = cache$.pluck;
  assert = {
    truthy: function (bool) {
      var cache$1, cache$2, explanation, name, negated;
      cache$1 = handleArgs(this, [
        1,
        2
      ], arguments, 'truthy');
      name = cache$1[0];
      negated = cache$1[1];
      if (arguments.length === 2) {
        cache$2 = arguments;
        explanation = cache$2[0];
        bool = cache$2[1];
        cache$2;
      }
      if (!(!!bool ^ negated))
        throw error('Expected ' + red(stringify(bool)) + ' to be ' + name, explanation);
    },
    expect: function (bool) {
      handleArgs(null, 1, arguments, 'expect', function () {
        var suggestions, tips;
        tips = function (accum$) {
          var tip;
          for (var cache$1 = [
                'truthy',
                'equal',
                'deepEqual',
                'include'
              ], i$ = 0, length$ = cache$1.length; i$ < length$; ++i$) {
            tip = cache$1[i$];
            accum$.push(green(tip));
          }
          return accum$;
        }.call(this, []);
        suggestions = implodeNicely(tips, 'or');
        return 'Did you mean ' + suggestions + '?';
      });
      if (!bool)
        throw error('Expected ' + red(stringify(bool)) + ' to be truthy');
    },
    equal: function (expected, actual) {
      var cache$1, cache$2, explanation, name, negated;
      cache$1 = handleArgs(this, [
        2,
        3
      ], arguments, 'equal');
      name = cache$1[0];
      negated = cache$1[1];
      if (arguments.length === 3) {
        cache$2 = arguments;
        explanation = cache$2[0];
        expected = cache$2[1];
        actual = cache$2[2];
        cache$2;
      }
      if (negated) {
        if (expected === actual) {
          throw error('notEqual assertion expected ' + red(stringify(actual)) + ' to be exactly anything else', explanation);
        }
      } else if (expected !== actual) {
        throw error('Expected: ' + green(stringify(expected)) + '\nActually: ' + red(stringify(actual)), explanation);
      }
    },
    deepEqual: function (expected, actual) {
      var cache$1, cache$2, explanation, message, name, negated, rightLooks, wrongLooks;
      cache$1 = handleArgs(this, [
        2,
        3
      ], arguments, 'deepEqual');
      name = cache$1[0];
      negated = cache$1[1];
      if (arguments.length === 3) {
        cache$2 = arguments;
        explanation = cache$2[0];
        expected = cache$2[1];
        actual = cache$2[2];
        cache$2;
      }
      if (!(isEqual(expected, actual) ^ negated)) {
        wrongLooks = stringify(actual);
        if (negated)
          throw error('notDeepEqual assertion expected exactly anything else but\n' + red(wrongLooks), explanation);
        rightLooks = stringify(expected);
        message = wrongLooks === rightLooks ? 'deepEqual ' + green(rightLooks) + ' failed on something that\nserializes to the same result (likely some function)' : 'Expected: ' + green(rightLooks) + '\nActually: ' + red(wrongLooks);
        throw error(message, explanation);
      }
    },
    include: function (needle, haystack) {
      var cache$1, cache$2, contained, explanation, message, name, negated, problem, verb, what;
      cache$1 = handleArgs(this, [
        2,
        3
      ], arguments, 'include');
      name = cache$1[0];
      negated = cache$1[1];
      if (arguments.length === 3) {
        cache$2 = arguments;
        explanation = cache$2[0];
        needle = cache$2[1];
        haystack = cache$2[2];
        cache$2;
      }
      if (isString(haystack)) {
        if (needle === '') {
          what = negated ? 'always-failing test' : 'no-op test';
          throw error('' + what + ' detected: all strings contain the empty string!');
        }
        if (!(isString(needle) || isNumber(needle) || isRegExp(needle))) {
          problem = 'needs a RegExp/String/Number needle for a String haystack';
          throw new TypeError('' + name + ' ' + problem + '; you used:\n' + name + ' ' + green(stringify(haystack)) + ', ' + red(stringify(needle)));
        }
      } else if (!isArray(haystack)) {
        needle = stringify(needle);
        throw new TypeError('' + name + ' takes a String or Array haystack; you used:\n' + name + ' ' + red(stringify(haystack)) + ', ' + needle);
      }
      if (isString(haystack)) {
        if (isRegExp(needle)) {
          contained = haystack.match(needle);
        } else {
          contained = haystack.indexOf(needle) !== -1;
        }
      } else {
        contained = contains(haystack, needle);
      }
      verb = isRegExp(needle) ? 'match' : 'include';
      if (negated) {
        if (contained) {
          message = 'notInclude expected needle not to be found in haystack\n- needle: ' + stringify(needle) + '\nhaystack: ' + abbreviate('', haystack);
          if (isString(haystack) && isRegExp(needle)) {
            message += ', but found:\n';
            if (needle.global) {
              message += contained.map(function (s) {
                return '* ' + red(stringify(s));
              }).join('\n');
            } else {
              message += '* ' + red(stringify(contained[0]));
            }
          }
          throw error(message, explanation);
        }
      } else if (!contained) {
        throw error('' + name + ' expected needle to be found in haystack\n- needle: ' + stringify(needle) + '\nhaystack: ' + abbreviate('', haystack), explanation);
      }
    },
    match: function (regexp, string) {
      var cache$1, cache$2, called, count, explanation, matched, message, name, negated, oops, re;
      cache$1 = handleArgs(this, [
        2,
        3
      ], arguments, 'match');
      name = cache$1[0];
      negated = cache$1[1];
      if (arguments.length === 3) {
        cache$2 = arguments;
        explanation = cache$2[0];
        regexp = cache$2[1];
        string = cache$2[2];
        cache$2;
      }
      if (!((re = isRegExp(regexp)) && isString(string))) {
        string = abbreviate('string', string);
        called = '' + name + ' ' + stringify(regexp) + ', ' + red(string);
        if (!re) {
          oops = 'regexp arg is not a RegExp';
        } else {
          oops = 'string arg is not a String';
        }
        throw new TypeError('' + name + ': ' + oops + '; you used:\n' + called);
      }
      matched = regexp.test(string);
      if (negated) {
        if (!matched)
          return;
        message = 'Expected: ' + stringify(regexp) + '\nnot to match: ' + red(abbreviate('string', string));
        if (regexp.global) {
          count = string.match(regexp).length;
          message += '\nMatches: ' + red(count);
        }
        throw error(message, explanation);
      }
      if (matched)
        return;
      throw error('Expected: ' + stringify(regexp) + '\nto match: ' + red(abbreviate('string', string)), explanation);
    },
    throws: function (fn) {
      var cache$1, cache$2, err, explanation, name, negated;
      cache$1 = handleArgs(this, [
        1,
        2
      ], arguments, 'throws');
      name = cache$1[0];
      negated = cache$1[1];
      if (arguments.length === 2) {
        cache$2 = arguments;
        explanation = cache$2[0];
        fn = cache$2[1];
        cache$2;
      }
      if (typeof explanation === 'function') {
        fn = explanation;
        explanation = void 0;
      }
      if (!(typeof fn === 'function'))
        throw error('' + name + ' expects ' + green('a function') + ' but got ' + red(fn));
      try {
        fn();
      } catch (e$) {
        err = e$;
        if (negated)
          throw error('Threw an exception despite ' + name + ' assertion:\n' + err.message, explanation);
        return err;
      }
      if (negated)
        return;
      throw error("Didn't throw an exception as expected to", explanation);
    },
    hasType: function (expected, x) {
      var actual, cache$1, cache$2, called, explanation, message, name, negated, okTypes;
      cache$1 = handleArgs(this, [
        2,
        3
      ], arguments, 'hasType');
      name = cache$1[0];
      negated = cache$1[1];
      if (arguments.length === 3) {
        cache$2 = arguments;
        explanation = cache$2[0];
        expected = cache$2[1];
        x = cache$2[2];
        cache$2;
      }
      okTypes = [
        String,
        Number,
        RegExp,
        Array,
        Function,
        Object
      ];
      if (!in$(expected, okTypes)) {
        called = '' + name + ' ' + stringify(expected) + ', ' + red(stringify(x));
        throw new TypeError('' + name + ': expected arg is not one of ' + ('' + pluck(okTypes, 'name').join(', ') + '; you used:\n' + called));
      }
      actual = function () {
        switch (false) {
        case !isString(x):
          return String;
        case !isNumber(x):
          return Number;
        case !isRegExp(x):
          return RegExp;
        case !isArray(x):
          return Array;
        case !isFunction(x):
          return Function;
        default:
          return Object;
        }
      }.call(this);
      if (!(expected === actual ^ negated)) {
        message = 'Expected argument ' + stringify(x) + ' to be of type ' + expected.name;
        throw error(message, explanation);
      }
    }
  };
  nameNegative = function (name) {
    if (name === 'truthy')
      return 'falsey';
    return 'not' + name.charAt().toUpperCase() + name.slice(1);
  };
  for (var cache$1 = [
        'truthy',
        'equal',
        'deepEqual',
        'include',
        'match',
        'throws',
        'hasType'
      ], i$ = 0, length$ = cache$1.length; i$ < length$; ++i$) {
    name = cache$1[i$];
    assert[nameNegative(name)] = function (name) {
      return function () {
        return assert[name].apply('!', arguments);
      };
    }(name);
  }
  green = function (x) {
    return '\x1b[32m' + x + '\x1b[39m';
  };
  red = function (x) {
    return '\x1b[31m' + x + '\x1b[39m';
  };
  implodeNicely = function (list, conjunction) {
    var first, last;
    if (null == conjunction)
      conjunction = 'and';
    first = list.slice(0, -1).join(', ');
    last = list[list.length - 1];
    return '' + first + ' ' + conjunction + ' ' + last;
  };
  abbreviate = function (name, value, threshold) {
    var desc, str;
    if (null == threshold)
      threshold = 1024;
    if ((str = stringify(value)).length <= threshold)
      return str;
    desc = 'length: ' + value.length;
    if (isArray(value))
      desc += '; ' + str.length + ' JSON encoded';
    if (name)
      name += ' ';
    return '' + name + type(value) + '[' + desc + ']';
  };
  type = function (x) {
    if (isString(x))
      return 'String';
    if (isNumber(x))
      return 'Number';
    if (isRegExp(x))
      return 'RegExp';
    if (isArray(x))
      return 'Array';
    throw new TypeError('unsupported type: ' + x);
  };
  asRegExp = function (re) {
    var flags;
    flags = '';
    if (re.global)
      flags += 'g';
    if (re.multiline)
      flags += 'm';
    if (re.ignoreCase)
      flags += 'i';
    return '/' + re.source + '/' + flags;
  };
  toString = Object.prototype.toString;
  stringify = function (x) {
    var className, e, json;
    if (!(null != x))
      return '' + x;
    if (isRegExp(x))
      return asRegExp(x);
    json = JSON.stringify(x, function (key, val) {
      if (typeof val === 'function')
        return toString(val);
      if (isRegExp(val))
        return asRegExp(val);
      return val;
    });
    if (typeof x !== 'object' || contains([
        'Object',
        'Array'
      ], className = x.constructor.name))
      return json;
    if (x instanceof Error || /Error/.test(className)) {
      if (json === '{}')
        return x.stack;
      return '' + x.stack + '\nwith error metadata:\n' + json;
    }
    if (x.toString === toString)
      return className;
    try {
      return '' + className + '[' + x + ']';
    } catch (e$) {
      e = e$;
      return className;
    }
  };
  error = function (message, explanation) {
    if (null != explanation)
      message = 'Assertion failed: ' + explanation + '\n' + message;
    return new Error(message);
  };
  handleArgs = function (self, count, args, name, help) {
    var actual, actualArgs, argc, functionSource, max, message, n, negated, wanted, wantedArgCount, wantedArgNames;
    negated = false;
    if (isString(self)) {
      negated = true;
      name = nameNegative(name);
    }
    argc = args.length;
    if (argc === count)
      return [
        name,
        negated
      ];
    max = '';
    if (isArray(count) && in$(argc, count)) {
      n = count[count.length - 1];
      if (argc !== n || isString(args[0]))
        return [
          name,
          negated
        ];
      max = ',\nand when called with ' + n + ' args, the first arg must be a docstring';
    }
    if (isNumber(count)) {
      wantedArgCount = '' + count + ' argument';
    } else {
      wantedArgCount = count.slice(0, -1).join(', ');
      count = count.pop();
      wantedArgCount = '' + wantedArgCount + ' or ' + count + ' argument';
    }
    if (!(count === 1))
      wantedArgCount += 's';
    actualArgs = stringify([].slice.call(args)).slice(1, -1);
    functionSource = Function.prototype.toString.call(assert[name]);
    wantedArgNames = functionSource.match(/^function\s*[^(]*\s*\(([^)]*)/)[1];
    if (max)
      wantedArgNames = 'explanation, ' + wantedArgNames;
    wanted = '' + name + '(' + wantedArgNames + ')';
    actual = '' + name + '(' + actualArgs + ')';
    message = '' + green(wanted) + ' needs ' + (wantedArgCount + max) + '\nyour usage: ' + red(actual);
    if (typeof help === 'function')
      help = help();
    throw error(message, help);
  };
  if (null != ('undefined' !== typeof module && null != module ? module.exports : void 0)) {
    module.exports = assert;
  } else {
    global.assert = assert;
  }
  function in$(member, list) {
    for (var i = 0, length = list.length; i < length; ++i)
      if (i in list && list[i] === member)
        return true;
    return false;
  }
}.call(this);
